version: 2.1
jobs:
  build:
    working_directory: ~/cours-l2
    docker:
      - image: circleci/node:10.16.3
    steps:
      steps:
        - checkout
        #      - run:
        #          name: test javascript exercices
        #          command: yarn global add jest && cd javascript && ~/.yarn/bin/jest javascript/test.js && cd ..
        #      - run:
        #          name: test button
        #          command: cd button && yarn install & yarn test && cd ..
        #      - run:
        #          name: test timer
        #          command: cd timer && yarn install & yarn test && cd ..
        - store_artifacts:
            path: test-results.xml
            prefix: tests

          version: 2.1
          jobs:
            build:
              working_directory: ~/cours-l2
              docker:
                - image: circleci/node:10.16.3
              steps:
                - checkout
                - run:
                  name: test javascript exercices
                  command: yarn global add jest && cd javascript && ~/.yarn/bin/jest javascript/test.js && cd ..
                - run:
                  name: test button
                  command: cd button && yarn install & cd src & cd components && yarn install && cd button && yarn install && yarn test Button.test.js && cd .. && cd .. && cd .. && cd ..
                - run:
                  name: test timer
                  command: cd timer && yarn install & cd src & cd components && yarn install && cd timer && yarn install && yarn test Timer.test.js && cd .. && cd .. && cd .. && cd ..
                - store_artifacts:
                    path: test-results.xml
                    prefix: tests
